### PR TITLE
fix typos in page front matter

### PR DESCRIPTION
**Pull request by tobyhodges**
`"` and `.` were misordered in the front matter of a few pages, causing the pages to build with title, objectives, key points etc missing. (See https://datacarpentry.org/python-ecology-lesson-es/01-short-introduction-to-Python/index.html as an example.)

This PR fixes these errors to get the pages displaying correctly again.

### CODE REVIEW

**Comment by orchid00** [comment]
hi @tobyhodges long ago you sent this PR. Thanks for that, how do we fix failed checks before merging?

**Comment by tobyhodges** [comment]
I think the answer to the failing checks is to bring in the latest changes to the lesson template. The template now uses GitHub Actions instead of Travis to check and build the lesson site. That is best kept for a separate Pull Request, which I am happy to put in if you like? 

Regardless, I have built and checked this branch locally and I believe this PR can be merged without fear of a broken lesson site.

**Comment by raynamharris** [comment]
LGTM. Thanks @tobyhodges and @orchid00

**Review by vinisalazar — APPROVED** [review]
@tobyhodges thank you for the contribution. I just built this PR's branch locally and everything seems to be fine.

@orchid00 @raynamharris is it okay for me to merge this? It would also help with #75, which in turn will help with fixing the failed Travis checks.

Thanks,
Vini

**Comment by raynamharris** [comment]
Looks good to me. Okay to merge this one and update the styles. Thank you!

**Pull request merged**
